### ISSUE TITLE
Does this open source project support the study of the effect of surface roughness on the deformation behavior of flexible plates in flow fields？

### ISSUE THREAD

**Issue by Badtreater** [KVSlab/turtleFSI#86]
Dear developers，
It is my honor to write this letter！ I hope to investigate the effect of surface roughness on the deformation behavior of flexible plates in flow fields. However, due to a lack of understanding of the underlying logic of the project, I am not sure whether this open project can achieve my expected goals and whether there is complete validation of reference data and literature. I hope to receive a response from the developers, and I will be very grateful! Thank you!

**Comment by keiyamamo** [comment]
Dear @Badtreater

`turtleFSI` is a general software for fluid-structure interaction simulation and it is definitely possible to investigate what you described with `turtleFSI`. Practically speaking, you need to first have a mesh which is not supported in this software, and you also need to know the basics of how to use finite element software called `FEniCS` as `turtleFSI` is built upon it. The difficulty of former heavily depends on your knowledge and experience while the latter is fairly straightforward because there are many great examples and large user community with `FEniCS`. If you’re motivated, I would first suggest running some problem files that are already in `turtleFSI`, such as [turtle_demo](https://github.com/KVSlab/turtleFSI/blob/master/turtleFSI/problems/turtle_demo.py) and [TF_fsi](https://github.com/KVSlab/turtleFSI/blob/master/turtleFSI/problems/TF_fsi.py). `TF_fsi` is a classical FSI benchmark problem (https://kratosmultiphysics.github.io/Examples/fluid_structure_interaction/validation/fsi_turek_FSI2/) and can be used for validation.

**Comment by Badtreater** [comment]
Thank you so much！！！！！！！！！！！！！！！！！！！！！！！！！！


| |
Tayir
|
|
***@***.***
|
On 9/16/2023 16:50，Kei ***@***.***> wrote：

Dear @Badtreater

turtleFSI is a general software for fluid-structure interaction simulation and it is definitely possible to investigate what you described with turtleFSI. Practically speaking, you need to first have a mesh which is not supported in this software, and you also need to know the basics of how to use finite element software called FEniCS as turtleFSI is built upon it. The difficulty of former heavily depends on your knowledge and experience while the latter is fairly straightforward because there are many great examples and large user community with FEniCS. If you’re motivated, I would first suggest running some problem files that are already in turtleFSI, such as turtle_demo and TF_fsi. TF_fsi is a classical FSI benchmark problem (https://kratosmultiphysics.github.io/Examples/fluid_structure_interaction/validation/fsi_turek_FSI2/) and can be used for validation.
